name: scikit-reducedmodel

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r

      - name: Install package
        run: pip install . pytest pytest-cov arby
      - name: generate .coverage report
        run: pytest tests/ --cov=skreducedmodel/ --cov-append --cov-report=term-missing
      - name: transform .coverage into coverage.xml
        run: coverage xml

      # Creating the badge
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
          files: /home/runner/work/scikit-reducedmodel/scikit-reducedmodel/coverage.xml
